name: Emscripten CI

on: [push]

jobs:
  build:
    runs_on: ubuntu-latest

    steps:
    - name: clone emsdk
      run:  git clone https://github.com/emscripten-core/emsdk.git
    - name: 
      run: ls && ./emsdk install latest
      working_dir: $GITHUB_WORKSPACE
