name: Emscripten CI for wasm-vips

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [node, web]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: compile wasm-wips for node and web
      env:
        COMMAND: ${{ matrix.command }}
      run: npm run build:$COMMAND

    - name: inspect directory to view artifacts etc
      run: ls -ahl
    
    - name: install dependencies for running tests
      run: npm install

    - name: run test
      run: npm run test:$COMMAND

    - name: "run benchmark"
      run: npm run bench
