name: Emscripten CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install python3
      run: apt-get -y install python3 cmake
    - name: clone emsdk
      run:  git clone https://github.com/emscripten-core/emsdk.git
    - name: list working directory
      run: ls && ./emsdk install latest
      working_dir: $GITHUB_WORKSPACE/emsdk
    - name: install, activate and source
      run: ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh 
      working_dir: $GITHUB_WORKSPACE/emdsk
 
