name: Emscripten CI for wasm-vips

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['npm run build:node', 'npm run build:web']
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: compile wasm-wips for node and web
      run: ${{ matrix.command }}

    - name: inspect directory to view artifacts etc
      run: ls -ahl
